# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Greet new contributor

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  greet:
    uses: friendly-fhir/.github/.github/workflows/community-greet-new-contributor.yaml@master
    permissions:
      contents: read
      issues: write
      pull-requests: write
    secrets: inherit
