# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check for Stale Issues and Pull Requests

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  greet:
    uses: friendly-fhir/.github/.github/workflows/community-stale-check.yaml@master
    permissions:
      contents: read
      issues: write
      pull-requests: write
    secrets: inherit
