# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Github Pages
on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-coverage

      - name: Generate Documentation
        run: mkdocs build

      # Some of the doc generation steps above create the directories with
      # 0750 for permissions -- which is triggering warning annotations in the
      # workflow summaries. Manually converting this to 0755 helps to suppress
      # this.
      - name: Fix permissions
        run: |
          find ./dist -type d -exec chmod 0755 {} \;
          find ./dist -type f -name '.lock' -delete

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: docs

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Upload GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
