# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Github Pages
on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-documentation:
    name: Generate Documentation
    uses: ./.github/workflows/build-docs.yaml

  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: generate-documentation

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Upload GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
