# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Postsubmit

on:
  workflow_call:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  id-token: write
  actions: read

jobs:
  build-and-test:
    name: Build and Test
    uses: friendly-fhir/.github/.github/workflows/go-build-and-test.yaml@master
    with:
      packages: ./...
      go-version-file: go.mod
      short-test: false
    permissions:
      contents: read
      id-token: write

  snapshot-release:
    name: Snapshot Release
    uses: friendly-fhir/.github/.github/workflows/go-release.yaml@master
    with:
      snapshot: true
    permissions:
      contents: write
      attestations: write
      id-token: write

  email-on-failure:
    name: Email on Failure
    runs-on: ubuntu-latest
    needs:
      - build-and-test
      - snapshot-release
    if: always() && failure()
    continue-on-error: true
    steps:
      - name: Send email
        uses: friendly-fhir/.github/actions/community/send-email@master
        with:
          recipient: subscribers@ci.friendly-fhir.org
          api-key: ${{ secrets.MAILGUN_API_KEY }}
          subject: ${{ github.repository}} Post-submit failed
          body: |
            The post-submit workflow for ${{ github.repository }} failed.
            Please see ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for details.
