# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  security-events: write
  id-token: write
  actions: read

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/presubmit.yaml
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read

  release:
    name: Release
    needs: continuous-integration
    uses: friendly-fhir/.github/.github/workflows/go-release.yaml@master
    with:
      snapshot: false
    permissions:
      contents: write
      attestations: write
      id-token: write
